baseURL = "https://alexlwyen.com"
languageCode = "en-us"
title = "Alex Yen"
theme = "soho"

enableInlineShortcodes = true

summarylength = 10
enableEmoji = true

[params]
author = "Alex Yen"
description = "Email: alyen@ucsd.edu"

## Set one of:
# gravatar = "soho@example.com"
profilePicture = "images/yen_website.jpg"

copyright = "Alex Yen"
##license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"

## Set custom theme color.
# themeColor = "#fc2803"

## Set custom CSS and/or JS to override site defaults.
customCss = ["css/website.css"]
customJs = ["js/website.js"]

  ## Set as many as you want.
  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/alex-lw-yen"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/alwyen"

[menu]

  [[menu.main]]
  name = "Publications"
  weight = 300
  identifier = "publications"
  url = "/publications/"

  [[menu.main]]
  name = "Writing"
  weight = 400
  identifier = "writing"
  url = "/writing/"

  [[menu.main]]
  name = "CV"
  weight = 500
  identifier = "CV"
  url = "https://alexlwyen.com/CV/AlexYen_CV.pdf"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true # if false, you need to provide you own custom CSS
  style = "monokai"
  tabWidth = 4